version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    # ports:
    # - "5432:5432"
    environment:
      POSTGRES_USER: furrax 
      POSTGRES_PASSWORD: furrax
    volumes:
      - postgres:/var/lib/postgresql/data
  node:
    image: "node:12"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    command: "npm start"

volumes:
  postgres:
