query GetGames {
  games {
    id
    title
    author {
      email
    }
    ratings {
      value
    }
  }
}

query GetGame {
  game(recipeId: 1) {
    id
    title
    ratings {
      value
      user {
        nickname
      }
      date
    }
    author {
      id
      nickname
      email
    }
  }
}

mutation AddGame {
  addGame(game: {
    title: "New Game"
  }) {
    id
    ratings {
      value
    }
    author {
      nickname
    }
  }
}

mutation RateGame {
  rate(rate: {
    gameId: 3
    value: 4
  }) {
    id
    ratings {
      value
      user {
        email
      }
    }
  }
}